-- INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Text', 'uid', 'Fri, 14 Apr 2023 00:34:12 GMT', 'imageID');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Checkout this blue bird!', '1', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Blue Bird.jpg');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('I also have a bird but it is red', '2', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Red Bird.jpg');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('This is my 2 year old green bird', '3', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Green Bird.jpg');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('How is everybody doing today?', '4', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Just finished reading an amazing book, would highly recommend', '5', 'Fri, 14 Apr 2023 00:34:12 GMT', 'book.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Anyone taking ITMT430 this semester??', '7', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Hi friends who wants to study together tonight!?', '8', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('What is everyone doing this weekend?', '9', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('First post is anyone reading this?', '10', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Feeling a bit under the weather today, hoping to feel better soon', '11', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('You are my sunshine on a cloudy day', '12', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Finally finished this painting that I have been working on for weeks', '13', 'Fri, 14 Apr 2023 00:34:12 GMT', 'paint.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Just got back from a great vacation in Hawaii', '14', 'Fri, 14 Apr 2023 00:34:12 GMT', 'hawaii.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Trying out this new restaurant tonight, cant wait!', '15', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('I am so hungry', '16', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Feeling grateful for my friends and family today', '17', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('When you finally understand a topic after hours of studying...', '18', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Ramen is the best', '19', 'Fri, 14 Apr 2023 00:34:12 GMT', 'ramen.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('finished my last exam of the semester!', '20', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Coffee is the only thing getting me through this week', '21', 'Fri, 14 Apr 2023 00:34:12 GMT', 'coffee1.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Just tried a new restaurant and it was amazing! Highly recommend the tacos.', '22', 'Fri, 14 Apr 2023 00:34:12 GMT', 'taco.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Missing my best friend who moved away, cant wait to see her again soon', '23', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Finally finished my thesis paper! Time to celebrate with a night out with friends', '24', 'Fri, 14 Apr 2023 00:34:12 GMT', 'drinks.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('todays agenda: class, study, repeat', '25', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Who else was delayed by the green line today?', '26', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Only three more projects to go! Summer here I COME!', '27', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Just got my exam results back and I passed! Celebrating with a pizza party tonight', '28', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('i am TIRED', '29', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('My dog is napping', '30', 'Fri, 14 Apr 2023 00:34:12 GMT', 'nap.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Midterm season is here and Im already stressed out! Any tips for staying calm and focused?', '31', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Late-night study session at the library. Coffee, textbooks, and notes, here I come.', '32', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Feeling grateful for this beautiful day and all the little things in life', '33', 'Fri, 14 Apr 2023 00:34:12 GMT', 'sun.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('got accepted into the study abroad program!!', '34', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Today was a beautiful day', '35', 'Fri, 14 Apr 2023 00:34:12 GMT', 'campus.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Did anyone register for next semester yet', '36', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('What are some good book reccomendations?', '37', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Trying out this new recipe tonight, hope it turns out delicious', '38', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Cannot wait to go on vacation this summer!!', '39', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Summer is too hot', '40', 'Fri, 14 Apr 2023 00:34:12 GMT', 'summer.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Just finished a great workout! Feeling energized and ready to take on the day', '41', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('this is bibble', '42', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Bibble.jpg');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('already been a year since I adopted my dog. He has been the best addition to my life', '43', 'Fri, 14 Apr 2023 00:34:12 GMT', 'doggy.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('It does not matter how slowly you go as long as you do not stop', '44', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('I am learning French bonjour', '45', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Feeling nostalgic today and listening to some old-school tunes', '46', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('just finished a challenging hike and the view at the top was totally worth it!', '47', 'Fri, 14 Apr 2023 00:34:12 GMT', 'hike.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Hosting a study session tomorrow if anyone wants to join', '48', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('My lunch I made from scratch!', '49', 'Fri, 14 Apr 2023 00:34:12 GMT', 'lunch.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('A hero is not measured by the size of his strength, but by the strength of his heart', '50', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('Anyone finish their python homework', '45', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Enjoying a lazy Sunday with a good book and some coffee', '46', 'Fri, 14 Apr 2023 00:34:12 GMT', 'coffee.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('All we have to decide is what to do with the time that is given us', '47', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Just adopted a new puppy, say hello to my fur baby!', '48', 'Fri, 14 Apr 2023 00:34:12 GMT', 'puppy.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Missing my study abroad experience in Spain, cant wait to travel again someday', '49', 'Fri, 14 Apr 2023 00:34:12 GMT', 'spain.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`) VALUES ('There is no knowledge that is not power', '50', 'Fri, 14 Apr 2023 00:34:12 GMT');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('I am a Saiyan who was raised on Earth. My purpose is to fight to protect this planet.', '6', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Goku 1.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Power comes in response to a need, not a desire. You have to create that need.', '6', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Goku 2.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('The only way to grow stronger is to challenge yourself.', '6', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Goku 3.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Hello Professor Hajek', '6', 'Fri, 14 Apr 2023 00:34:12 GMT', 'Goku 4.png');
INSERT INTO `team6o`.`posts` (`caption`, `uid`, `created`, `image`) VALUES ('Hi everyone! Welcome to Hawkstagram', '7', 'Fri, 14 Apr 2023 00:34:12 GMT', 'hawk.png');

